[package]
name = "fact"
version = "0.1.0"
edition = "2021"

license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aya = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
uuid = { workspace = true }
which = { workspace = true }
crossbeam = { workspace = true }
ctrlc = { workspace = true }
nix = { workspace = true }
serde_json = { workspace = true }

fact-api = { path = "../fact-api" }
tokio-stream = "0.1.17"

[build-dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true }
tonic-build = { workspace = true }

[[bin]]
name = "fact"
path = "src/main.rs"
